openapi: 3.0.4
info:
  title: Reverse Geocode
  description: >-
    Reverse Geocode is a simple tool for getting the location of a set of
    coordinates. Only supports USA and Canada Coordinates. It returns the city,
    state, and more.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/reversegeocode:
    get:
      summary: Get Coordinate Details
      description: >-
        Get the location of a set of coordinates, Only supports USA and Canada
        Coordinates
      operationId: reversegeocode
      parameters:
        - name: lat
          in: query
          schema:
            type: number
          required: true
          description: The latitude of the coordinates
          example: 40.714224
        - name: lon
          in: query
          schema:
            type: number
          required: true
          description: The longitude of the coordinates
          example: -73.961452
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  zipcode: '11211'
                  state_abbr: NY
                  city: Brooklyn
                  state: New York
                  distance: 0.6501757300758664
                  latitudeClosest: '40.712090'
                  longitudeClosest: '-73.95427'
                  countryCode: US
                  latitude: 40.714224
                  longitude: -73.961452
                  estimatedCity: true
                  nearestCities:
                    - Brooklyn
                    - Brooklyn Park
                    - East Brooklyn
                    - Brooklyn Center
                    - Brooklyn Heights
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
